Numpy Kullanımı

In [3]:
import numpy as np

a = np.array([1,2,3,4,5,6,7,8])
b = np.array([1,2,3,4,5,6,7,8])
print(a * b)

[ 1  4  9 16 25 36 49 64]


Numpy Array'ı Oluşturmak

In [10]:
import numpy as np

a = np.array([1.2,2,3,4,5,6],dtype = "int")

In [5]:
type(a)

numpy.ndarray

Sıfırdan Array Oluşturma

In [12]:
np.zeros(10, dtype ="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((3,2),dtype="int")

array([[1, 1],
       [1, 1],
       [1, 1]])

In [17]:
np.full((4,7), 5,dtype="int")

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

Doğrusal Dizi Oluşturmak

In [19]:
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Ortalama ve Standart Sapmasını İstediğimiz Matris Oluşturma

In [21]:
np.random.normal(20,3,(2,2))

array([[18.91345037, 21.8024753 ],
       [18.44600213, 20.21842087]])

NOT!: Tek boyutlu array'ın karşılığı vektör, iki boyutlu array'ın karşılığı matris'tir.

In [23]:
np.random.randint(2,10,(2,3))

array([[9, 5, 7],
       [4, 5, 6]])

Özellikler: 

ndim: Boyut Sayısı |
shape: Boyut Bilgisi |
size: Toplam Eleman Sayısı |
dtype: Array Veri Tipi

In [27]:
a= np.random.randint(20, size = 10)
a

array([17, 12,  6,  9,  0,  6, 17, 11, 11,  5])

In [28]:
a.size

10

In [29]:
a.shape

(10,)

In [30]:
a.dtype

dtype('int64')

In [31]:
a.ndim

1

Yeniden Şekillendirme

In [47]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Birleştirme (Concatenate)

In [49]:
x = np.array([1,2,3])
y = np.array([5,6,7])


In [50]:
np.concatenate([x,y])

array([1, 2, 3, 5, 6, 7])

In [51]:
# İKİ BOYUT

a = np.array([[1,2,3],[4,5,6]])

In [52]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [54]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Array Ayırma (split)

In [56]:
x = np.array([1,2,3,4,5,6,7,8,9,23,34,56,78,89])

In [60]:
# AYRILAN DEĞERLERİ ATAMA

a,b,c,d,e,f = np.split(x, [2,3,5,7,9])

In [61]:
a

array([1, 2])

In [62]:
b

array([3])

In [63]:
c

array([4, 5])

In [64]:
d

array([6, 7])

In [65]:
e

array([8, 9])

In [66]:
f

array([23, 34, 56, 78, 89])

In [67]:
# İKİ BOYUTLU AYIRMA

a = np.arange(1,10).reshape((3,3))

In [70]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
np.vsplit(a, [2])

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]])]

In [71]:
ust, alt = np.vsplit(a, [2])

In [72]:
ust

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
alt

array([[7, 8, 9]])

In [75]:
np.hsplit(a, [2])

[array([[1, 2],
        [4, 5],
        [7, 8]]),
 array([[3],
        [6],
        [9]])]

In [76]:
sag, sol = np.hsplit(a, [2])

In [77]:
sag

array([[1, 2],
       [4, 5],
       [7, 8]])

In [78]:
sol

array([[3],
       [6],
       [9]])

Sıralama (sort)

In [79]:
v = np.array([1,2,3,4,5,6,7,8,9,34,45,56,67,78])

In [80]:
np.sort(v)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 34, 45, 56, 67, 78])

In [81]:
v.sort()

In [86]:
# İKİ BOYUTLU SIRALAMA

a = np.random.normal(24, 4, [4,4])

In [87]:
np.sort(a, axis=1)

array([[19.52228259, 21.51119571, 21.58784642, 30.91245857],
       [20.63702129, 22.93284827, 25.11570976, 25.72098675],
       [20.25001899, 22.53438475, 23.24451888, 23.53874662],
       [25.52697047, 27.72176114, 27.86007754, 31.44615605]])

In [88]:
np.sort(a, axis=0)

array([[20.63702129, 19.52228259, 23.53874662, 21.51119571],
       [21.58784642, 20.25001899, 25.11570976, 23.24451888],
       [22.53438475, 22.93284827, 27.86007754, 25.72098675],
       [31.44615605, 25.52697047, 30.91245857, 27.72176114]])

Slice İle Elemanlara Erişmek (Array'ın alt kümesine erişmek)

In [3]:
import numpy as np

a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
a [0::2]

array([20, 22, 24, 26, 28])

In [36]:
# İKİ BOYUTLU ARRAY'IN ALT KÜMESİNE ERİŞMEK

m = np.random.randint(30, size = (5,5))
m 

array([[ 0, 20, 11,  9, 29],
       [28, 20, 23, 23, 14],
       [18,  1, 19,  1,  1],
       [ 7, 18,  7, 14,  7],
       [29,  6,  2, 24, 14]])

In [40]:
m[1:3,:]

array([[28, 20, 23, 23, 14],
       [18,  1, 19,  1,  1]])

In [42]:
m[3,2:4]

array([ 7, 14])

In [68]:
# COPY METODU

a = np.random.randint(20, size=(5,5))
a

array([[ 8,  3, 12,  5, 11],
       [ 3, 19,  3, 15,  9],
       [ 2, 18,  9,  0,  3],
       [11, 10,  7,  8,  3],
       [12,  9,  3, 14,  6]])

In [75]:
alt = a[4,3:].copy()
alt

array([14,  6])

In [99]:
alt[0] = 123
alt

array([  123, 99999])

Fancy İndex İle Elemanlara Erişmek

In [3]:
import numpy as np
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
getir = [8,9,2,5]

In [5]:
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
a[getir]

array([24, 27,  6, 15])

In [12]:
# İKİ BOYUTTA FANCY

a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
satir = [0,1]
sutun = [2,1]

In [27]:
a[sutun]

array([[6, 7, 8],
       [3, 4, 5]])

In [38]:
# SLİCE İLE FANCY
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
a[1:, [0,2]]

array([[3, 5],
       [6, 8]])

Numpy İle İki Bilinmeyenli Denklem Çözme

In [50]:
import numpy as np
a = np.array([[7,1],[1,3]])
b = np.array([[45],[33]])
x = np.linalg.solve(a,b)
x

array([[5.1],
       [9.3]])